services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kotauth-website:latest
    container_name: kotauth-website
    ports:
      - 3004
      - 8080
    restart: unless-stopped
